services:
  nginx:
    image: 'nginx:1.21.3'
    container_name: nginx
    depends_on:
      - phpfpm
      - mysql
      - elastic
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./www:/var/www/html:cached
  phpfpm:
    build: './dockerfile/phpfpm'
    container_name: php74
    volumes:
      - ./www:/var/www/html:delegated
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:delegated
  mysql:
    image: mysql:5.7.35
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'magento'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
    - ./databases:/var/lib/mysql:cached
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elastic
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data:delegated
    ports:
      - 9200:9200
      - 9300:9300
# Network
networks:
    default:
      name: magento 

